### PR TITLE
Support parse xrepo fetch --json.

### PR DESCRIPTION
**Pull request by cyfdecyf**
Use `xrepo fetch --json` to fetch package information.

### CODE REVIEW

**Comment by cyfdecyf** [comment]
Just saw this [log](https://github.com/xmake-io/xrepo-cmake/runs/4831441370?check_suite_focus=true#step:4:21) in github actions:

```
error: execv(xmake require --fetch --fetch_modes=json --extra={system=false} tbox) failed(-1)
```

I need to find a reliable way to detect whether xrepo fetch supports `--json` option.

**Comment by waruqi** [comment]
> Just saw this [log](https://github.com/xmake-io/xrepo-cmake/runs/4831441370?check_suite_focus=true#step:4:21) in github actions:
> 
> ```
> error: execv(xmake require --fetch --fetch_modes=json --extra={system=false} tbox) failed(-1)
> ```
> 
> I need to find a reliable way to detect whether xrepo fetch supports `--json` option.

try `xrepo fetch --help | grep "--json"` , find string in cmake

**Comment by waruqi** [comment]
I have updated xmake to support c++ command and fix ci. so I merged it first. you can open a new pr if you want to continue to improve it.

BTW, `xrepo fetch` maybe will return `{defines = "", syslinks = "", cflags = "", ldflags = ""}`, e.g. pcre2 package

**Comment by cyfdecyf** [comment]
> BTW, `xrepo fetch` maybe will also return `{defines = "", syslinks = "", cflags = "", ldflags = ""}`, e.g. pcre2 package

For existing CMake projects, the ideal situation is that package provides cmake modules that provides all thoses definitions in various library properties. So the user just need to call `target_link_libraries` with the correct library.

If a package does not provide cmake modules, the current situation is that the user has to figure out all the necessary parts by themselfs. `xrepo-cmake` indeed can provide help on this, but it still requires the user to figure out what is necessary.

I plan to focus on using Xrepo in my projects for the next week and see what features are still missing.

**Pull request merged**
